# Generated by Django 5.1.6 on 2025-03-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20250326_1301'),
    ]

    operations = [
    ]
