# Generated by Django 5.1.6 on 2025-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_booking_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_number',
            field=models.IntegerField(default='2'),
        ),
    ]
